# Generated by Django 4.0.6 on 2022-08-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_csv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=100)),
                ('movie_name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
