# Generated by Django 4.0.6 on 2022-08-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_csv', '0003_alter_csv_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='activated',
            new_name='success',
        ),
    ]
