# Generated by Django 2.2.5 on 2022-08-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_csv', '0004_rename_activated_csv_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
