# Generated by Django 4.0.6 on 2022-08-09 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('import_csv', '0006_alter_csv_id_alter_movie_id_movieuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MovieUser',
        ),
    ]
