# Generated by Django 4.0.6 on 2022-08-10 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('import_csv', '0007_movie_movie_user_delete_movieuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
