# Generated by Django 4.0.6 on 2022-09-23 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('import_csv', '0008_alter_movie_movie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_level', models.CharField(choices=[('ADVANCED', 'Advanced'), ('INTERMEDIATE', 'Intermediate'), ('BEGINNER', 'Beginner')], default='INTERMEDIATE', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
